frutas = ("maça", "uva", "tomate", "uva", "kiwi")
print(frutas)
print((len(frutas)))
print(frutas.count("uva"))
print(frutas[3])
print(type(frutas))
misto = ("alface", 23, True, 7.33)
print(misto)
print(type(misto))