print("Digite o valor do comprimento do retângulo:")
comprimento = float(input())
print("Digite o valor da largura do retângulo:")
largura = float(input())
print("A área do seu retângulo é:", comprimento * largura)